# Generated by Django 4.1 on 2022-09-07 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="Title")),
                ("content", models.TextField(verbose_name="Content")),
                ("image", models.URLField(verbose_name="Image URL")),
                (
                    "publish_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Publish Date"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Last Updated Date"
                    ),
                ),
                ("status", models.CharField(max_length=50, verbose_name="Status")),
                ("slug", models.IntegerField(verbose_name="Slug")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
