# Generated by Django 4.1 on 2022-09-08 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_category_alter_post_slug_alter_post_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
