# Generated by Django 4.1 on 2022-09-08 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_comment_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="postcomment",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="blog.post"
            ),
            preserve_default=False,
        ),
    ]
