# Generated by Django 4.1 on 2022-09-09 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_alter_like_like_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="like",
            name="post_like",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="blog.post"
            ),
        ),
    ]
