# Generated by Django 4.1 on 2022-09-10 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0012_alter_post_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="post",
        ),
        migrations.AddField(
            model_name="post",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="blog.category",
            ),
            preserve_default=False,
        ),
    ]
