# Generated by Django 4.1 on 2022-09-10 08:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0015_remove_category_post_post_category_alter_post_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="like",
            name="like_user",
        ),
        migrations.AddField(
            model_name="like",
            name="like_user",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
