# Generated by Django 4.1 on 2022-09-10 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0016_remove_like_like_user_like_like_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="like",
            name="like_user",
        ),
        migrations.AddField(
            model_name="post",
            name="like",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="blog.like"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="like",
            name="post_like",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
