# Generated by Django 4.1 on 2022-09-10 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0017_remove_like_like_user_post_like_alter_like_post_like"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="like",
        ),
    ]
