# Generated by Django 4.1 on 2022-09-10 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0018_remove_post_like"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="time_stamp",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Time, comment added"
            ),
        ),
    ]
