# Generated by Django 4.1 on 2022-09-10 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0019_alter_comment_time_stamp"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="postcomment",
        ),
    ]
