# Generated by Django 4.1 on 2022-09-10 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0020_remove_comment_postcomment"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="postcomment",
            field=models.ManyToManyField(to="blog.post"),
        ),
    ]
