# Generated by Django 4.1 on 2022-09-12 03:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0024_alter_comment_postcomment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelOptions(
            name="post",
            options={"verbose_name_plural": "Post"},
        ),
        migrations.RenameField(
            model_name="like",
            old_name="post_like",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="user",
            new_name="author",
        ),
        migrations.RenameField(
            model_name="post_view",
            old_name="post_view",
            new_name="post",
        ),
        migrations.RemoveField(
            model_name="like",
            name="like",
        ),
        migrations.RemoveField(
            model_name="post_view",
            name="viewed_user",
        ),
        migrations.AddField(
            model_name="like",
            name="post",
            field=models.ForeignKey(
                default=2, on_delete=django.db.models.deletion.CASCADE, to="blog.post"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="post_view",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Category Title"),
        ),
        migrations.AlterField(
            model_name="comment",
            name="postcomment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="blog.post"
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="time_stamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="blog.category"
            ),
        ),
    ]
