# Generated by Django 4.1 on 2022-09-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0026_rename_postcomment_comment_post_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post_view",
            name="view_time",
            field=models.DateTimeField(unique=True, verbose_name="View Time"),
        ),
    ]
