# Generated by Django 4.1 on 2022-09-16 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0027_alter_post_view_view_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post_view",
            name="view_time",
            field=models.DateTimeField(
                auto_now_add=True, unique=True, verbose_name="View Time"
            ),
        ),
    ]
